version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-peliculas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: peliculas
      MYSQL_DATABASE: code_peliculas
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
